name: Use .env from GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Choose branch"
        required: true
        default: "main" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Create folder and write .env file
      run: |
        mkdir -p backend/config
        echo "${{ secrets.PLATFORM }}" > backend/config/.env

    - name: Show  of .env file (for testing only - remove later)
      run: cat backend/config/.env
