name: Use .env from GitHub Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create folder and write .env file
      run: |
        mkdir -p backend/config
        echo "${{ secrets.PLATFORM }}" > backend/config/.env

    - name: Show contents of .env file (for testing only - remove later)
      run: cat backend/config/.env
