name: Use .env from GitHub Secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.event.inputs.branch }}

    steps:
    - name: Print branch name
      run: |
        echo "Branch selected: $BRANCH_NAME"
