name: Use .env from GitHub Secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Save branch name as an environment variable
      run: |
        echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV

    - name: Create folder and write .env file
      run: |
        mkdir -p backend/config
        echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" > backend/config/.env

    - name: Show .env file (for testing only - remove later)
      run: cat backend/config/.env